### ISSUE TITLE
There is no beer_data_fin.csv in this repo

### ISSUE THREAD

**Issue by kiwimic** [datadiarist/large_files#1]
https://datadiarist.github.io/post/building-a-recommendation-system-with-beer-data/

I read your article, and wanted to reproduce code. But I can't find beer_data_fin.csv on  your repos. In beer1 to beer4 csv files. There are no columns with beer styles (style2)

**Comment by datadiarist** [comment]
Thanks for reading the article.  Currently, the only data that I'm making available is the ratings, beer names, and anonymized user ids.  However, I'd be happy to send you the beer style data as well.  Do you have an email?

**Comment by kiwimic** [comment]
Yes, michalsiwik@gmail.com, do you have some license problems?

śr., 11.09.2019, 14:35 użytkownik datadiarist <notifications@github.com>
napisał:

**Comment by datadiarist** [comment]
Okay.  Emailed you the data.  Let me know if there's issues.  I should mention that some of the characters (e.g. apostrophes) were altered when I reentered it into R, so you may have to make some modifications.  However, merging the styles into the full beer df should work for ~90% of beers using the left_join function from dplyr.
